"""empty message

Revision ID: 516f55fb3e43
Revises: 
Create Date: 2024-06-07 13:44:39.891327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516f55fb3e43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('contents', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('sessions', sa.JSON(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('surname', sa.UnicodeText(), nullable=False),
    sa.Column('specialty', sa.UnicodeText(), nullable=True),
    sa.Column('job', sa.UnicodeText(), nullable=True),
    sa.Column('mail', sa.UnicodeText(), nullable=True),
    sa.Column('vk', sa.UnicodeText(), nullable=True),
    sa.Column('tg', sa.UnicodeText(), nullable=True),
    sa.Column('city', sa.UnicodeText(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('avatar_ref', sa.Text(), nullable=True),
    sa.Column('about', sa.UnicodeText(), nullable=True),
    sa.Column('skills', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_ref'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_ref', sa.Text(), nullable=False),
    sa.Column('date', sa.Double(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('type', sa.UnicodeText(), nullable=True),
    sa.Column('original', sa.UnicodeText(), nullable=True),
    sa.Column('translation', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('thumbnail_ref', sa.Text(), nullable=True),
    sa.Column('content_ref', sa.Text(), nullable=True),
    sa.Column('preview_original', sa.UnicodeText(), nullable=True),
    sa.Column('preview_translation', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['content_ref'], ['file.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_ref'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_ref'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('file')
    # ### end Alembic commands ###
