"""empty message

Revision ID: 205268625e17
Revises: 
Create Date: 2024-05-13 03:26:32.008706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205268625e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_model',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('contents', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('surname', sa.UnicodeText(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('avatar_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_ref'], ['file_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_model',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('user_ref', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_ref'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_model')
    op.drop_table('user_model')
    op.drop_table('file_model')
    # ### end Alembic commands ###
